/*
 * @Author: coderzhaolu && izhaicy@163.com
 * @Date: 2022-06-22 11:13:07
 * @LastEditors: coderzhaolu && izhaicy@163.com
 * @LastEditTime: 2022-08-07 08:54:18
 * @FilePath: /pinkmoe_server/model/response/errors.go
 * @Description: https://github.com/Coder-ZhaoLu/pinkmoe   (如需用于商业用途或者二开，请联系作者捐助任意金额即可)
 * QQ:2419857357;支付宝:13135986153
 * Copyright (c) 2022 by coderzhaolu, All Rights Reserved.
 */
package response

import "errors"

var (
	ErrorLoginLogUpdate          = errors.New("用户登陆日志更新失败")
	ErrorLoginLogListGet         = errors.New("用户登陆日志获取失败")
	ErrorUserOnlineListGet       = errors.New("用户在线获取失败")
	ErrorUserOnlineUpdate        = errors.New("用户在线更新失败")
	ErrorEmailSend               = errors.New("邮箱发送失败")
	ErrorEmailTitle              = errors.New("邮箱标题类型错误")
	ErrorEmailContent            = errors.New("邮箱内容类型错误")
	ErrorEmailExist              = errors.New("邮箱已存在")
	ErrorJwtToken                = errors.New("token解析失败")
	ErrorValidateCode            = errors.New("验证码错误")
	ErrorUserNotLogin            = errors.New("用户未登录")
	ErrorUserLogout              = errors.New("退出登陆失败")
	ErrorUserCreate              = errors.New("用户创建失败")
	ErrorUserUpdate              = errors.New("用户更新失败")
	ErrorCheckIned               = errors.New("今日已签到")
	ErrorCheckIn                 = errors.New("用户签到失败")
	ErrorUserDel                 = errors.New("用户删除失败")
	ErrorUserAuthDel             = errors.New("用户角色删除失败")
	ErrorUserNotExist            = errors.New("用户不存在")
	ErrorUserOnlineCreate        = errors.New("创建用户在线日志失败")
	ErrorUserOnlineDelete        = errors.New("删除用户在线日志失败")
	ErrorLoginLogCreate          = errors.New("创建登陆日志失败")
	ErrorLoginLogDelete          = errors.New("删除登陆日志失败")
	ErrorUserNotDel              = errors.New("不能删除自己")
	ErrorUserEmailExist          = errors.New("用户邮箱已存在")
	ErrorInvalidPassword         = errors.New("密码错误")
	ErrorMenuGet                 = errors.New("获取菜单失败")
	ErrorMenuDel                 = errors.New("菜单删除失败")
	ErrorMenuDelChild            = errors.New("此菜单存在子菜单")
	ErrorMenuUpdate              = errors.New("更新菜单失败")
	ErrorMenuName                = errors.New("菜单标识已存在")
	ErrorMenuCreate              = errors.New("创建菜单失败")
	ErrorJwtCreate               = errors.New("jwt加入黑名单失败")
	ErrorUserMeta                = errors.New("用户信息错误")
	ErrorUserMetaGet             = errors.New("获取用户信息错误")
	ErrorCreateNotification      = errors.New("创建通知错误")
	ErrorGetNotification         = errors.New("获取通知错误")
	ErrorChatListGet             = errors.New("获取聊天列表错误")
	ErrorChatRelationGet         = errors.New("获取聊天关系错误")
	ErrorChatRelationCreate      = errors.New("创建聊天关系错误")
	ErrorChatRelationDelete      = errors.New("删除聊天关系错误")
	ErrorChatCreate              = errors.New("创建聊天关系错误")
	ErrorPostListGet             = errors.New("获取文章列表错误")
	ErrorPostDownloadBuy         = errors.New("购买文章下载错误")
	ErrorPostDownloadCashBuy     = errors.New("购买文章下载现金不足")
	ErrorPostDownloadCreditBuy   = errors.New("购买文章下载积分不足")
	ErrorPostMusicBuy            = errors.New("购买文章音乐错误")
	ErrorPostMusicCashBuy        = errors.New("购买文章音乐现金不足")
	ErrorPostMusicCreditBuy      = errors.New("购买文章音乐积分不足")
	ErrorPostVideoBuy            = errors.New("购买文章视频错误")
	ErrorPostVideoCashBuy        = errors.New("购买文章视频现金不足")
	ErrorPostVideoCreditBuy      = errors.New("购买文章视频积分不足")
	ErrorPostCollect             = errors.New("获取收藏文章失败")
	ErrorPostCollected           = errors.New("文章已经被收藏")
	ErrorPostUnCollected         = errors.New("文章未被收藏")
	ErrorPostUpdate              = errors.New("更新文章错误")
	ErrorPostCreate              = errors.New("创建文章错误")
	ErrorPostDelete              = errors.New("删除文章错误")
	ErrorCategoryUpdate          = errors.New("更新分类错误")
	ErrorCategoryDel             = errors.New("删除分类错误")
	ErrorCategoryCreate          = errors.New("创建分类错误")
	ErrorCategoryDelBychild      = errors.New("此分类下有子分类")
	ErrorCategoryDelByPost       = errors.New("此分类下有文章")
	ErrorGoodsCategoryUpdate     = errors.New("更新商品分类错误")
	ErrorGoodsCategoryDel        = errors.New("删除商品分类错误")
	ErrorGoodsCategoryCreate     = errors.New("创建商品分类错误")
	ErrorGoodsCategoryDelBychild = errors.New("此分类下有子分类")
	ErrorGoodsCategoryDelByPost  = errors.New("此分类下有文章")
	ErrorSettingGet              = errors.New("获取设置项错误")
	ErrorSettingUpdate           = errors.New("更新设置项错误")
	ErrorSettingCreate           = errors.New("创建设置错误")
	ErrorFileListGet             = errors.New("获取文件列表错误")
	ErrorTopicListGet            = errors.New("获取话题列表错误")
	ErrorPostTopicDelete         = errors.New("删除文章话题错误")
	ErrorTopicUpdate             = errors.New("更新话题错误")
	ErrorTopicCreate             = errors.New("创建话题错误")
	ErrorTopicDelete             = errors.New("删除话题错误")
	ErrorBuyCredit               = errors.New("购买积分错误")
	ErrorBuyCash                 = errors.New("充值现金错误")
	ErrorCash                    = errors.New("用户现金不足")
	ErrorKeyUsed                 = errors.New("卡密错误或已经被使用")
	ErrorPayChoose               = errors.New("请选择正确的充值项")
	ErrorKeyListGet              = errors.New("获取卡密列表错误")
	ErrorKeyUpdate               = errors.New("更新卡密错误")
	ErrorKeyCreate               = errors.New("创建卡密错误")
	ErrorKeyDelete               = errors.New("删除卡密错误")
	ErrorFileUpload              = errors.New("文件上传错误")
	ErrorFileDelete              = errors.New("文件删除错误")
	ErrorOperationListGet        = errors.New("获取操作日志列表错误")
	ErrorOperationUpdate         = errors.New("更新操作日志错误")
	ErrorOperationCreate         = errors.New("创建操作日志错误")
	ErrorOperationDelete         = errors.New("删除操作日志错误")
	ErrorCommentListGet          = errors.New("获取评论列表错误")
	ErrorCommentUpdate           = errors.New("更新评论错误")
	ErrorCommentCreate           = errors.New("创建评论错误")
	ErrorCommentDelete           = errors.New("删除评论错误")
	ErrorAuthorityListGet        = errors.New("获取角色列表错误")
	ErrorAuthorityCreate         = errors.New("创建角色错误")
	ErrorAuthorityMenuCreate     = errors.New("创建角色菜单错误")
	ErrorAuthorityUpdate         = errors.New("更新角色错误")
	ErrorAuthorityDelByUser      = errors.New("此角色有用户正在使用")
	ErrorAuthoritySame           = errors.New("存在相同角色ID")
	ErrorAuthorityDel            = errors.New("此角色删除失败")
	ErrorAuthorityParamsGet      = errors.New("获取角色参数错误")
	ErrorAuthorityMenuGet        = errors.New("获取角色菜单错误")
	ErrorAuthorityMenuUpdate     = errors.New("更新角色菜单错误")
	ErrorApiGet                  = errors.New("api获取错误")
	ErrorApiBoth                 = errors.New("存在相同api")
	ErrorApiCreate               = errors.New("api创建失败")
	ErrorApiDel                  = errors.New("api删除失败")
	ErrorApiUpdate               = errors.New("api更新失败")
	ErrorApiCountGet             = errors.New("api数量获取错误")
	ErrorCasbinUpdate            = errors.New("权限更新失败")
	ErrorUserFollowListGet       = errors.New("获取关注列表失败")
	ErrorUserFollowCountGet      = errors.New("获取关注数量失败")
	ErrorUserFansCountGet        = errors.New("获取粉丝数量失败")
	ErrorUserFollowStatusGet     = errors.New("获取关注状态失败")
	ErrorUserFollow              = errors.New("关注用户失败")
	ErrorUserUnFollow            = errors.New("取消关注用户失败")
	ErrorUserFollowed            = errors.New("已经关注此用户")
	ErrorUserFolloweOwn          = errors.New("不能关注自己")
	ErrorUserUnFolloweOwn        = errors.New("不能取消关注自己")
	ErrorUserLevel               = errors.New("无法开通低于您等级的会员")
	ErrorCashTakeOut             = errors.New("扣除现金失败")
	ErrorBuyVip                  = errors.New("开通会员失败")
	ErrorTaskGet                 = errors.New("获取任务项错误")
	ErrorTaskUpdate              = errors.New("更新任务项错误")
	ErrorTaskCreate              = errors.New("创建任务错误")
)
