// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Article: typeof import('./../src/components/Article/index.vue')['default']
    Authorlayout: typeof import('./../src/components/Authorlayout/index.vue')['default']
    Basicinput: typeof import('./../src/components/Basicinput/index.vue')['default']
    Bbsarticle: typeof import('./../src/components/Bbsarticle/index.vue')['default']
    Commentcontent: typeof import('./../src/components/Commentcontent/index.vue')['default']
    Commentfont: typeof import('./../src/components/Commentfont/index.vue')['default']
    Commentsmile: typeof import('./../src/components/Commentsmile/index.vue')['default']
    Dialog: typeof import('./../src/components/Dialog/index.vue')['default']
    Footer: typeof import('./../src/components/Footer/index.vue')['default']
    GlobalNotice: typeof import('./../src/components/GlobalNotice/index.vue')['default']
    Greenbtn: typeof import('./../src/components/Greenbtn/index.vue')['default']
    Header: typeof import('./../src/components/Header/index.vue')['default']
    Headerrecategory: typeof import('./../src/components/Headerrecategory/index.vue')['default']
    Login: typeof import('./../src/components/Login/index.vue')['default']
    Message: typeof import('./../src/components/Message/index.vue')['default']
    Mobile: typeof import('./../src/components/Mobile/index.vue')['default']
    Morebtn: typeof import('./../src/components/Morebtn/index.vue')['default']
    Msgconfirm: typeof import('./../src/components/Msgconfirm/index.vue')['default']
    NotFound: typeof import('./../src/components/NotFound/index.vue')['default']
    Postcomment: typeof import('./../src/components/Postcomment/index.vue')['default']
    Postdownload: typeof import('./../src/components/Postdownload/index.vue')['default']
    Postmusic: typeof import('./../src/components/Postmusic/index.vue')['default']
    Postvideo: typeof import('./../src/components/Postvideo/index.vue')['default']
    Publishcategory: typeof import('./../src/components/Publishcategory/index.vue')['default']
    Publishcomment: typeof import('./../src/components/Publishcomment/index.vue')['default']
    Publishrecategory: typeof import('./../src/components/Publishrecategory/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./../src/components/Search/index.vue')['default']
    Searchrecategory: typeof import('./../src/components/Searchrecategory/index.vue')['default']
    Shopconfirm: typeof import('./../src/components/Shopconfirm/index.vue')['default']
    Slideauthor: typeof import('./../src/components/Slideauthor/index.vue')['default']
    Slidecomment: typeof import('./../src/components/Slidecomment/index.vue')['default']
    Slidepost: typeof import('./../src/components/Slidepost/index.vue')['default']
    Slideuser: typeof import('./../src/components/Slideuser/index.vue')['default']
    Spin: typeof import('./../src/components/Spin/index.vue')['default']
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default']
    TextareaInput: typeof import('./../src/components/TextareaInput/index.vue')['default']
    Usercenterlayout: typeof import('./../src/components/Usercenterlayout/index.vue')['default']
    Vipconfirm: typeof import('./../src/components/Vipconfirm/index.vue')['default']
    Wangeditor: typeof import('./../src/components/Wangeditor/index.vue')['default']
    Whitebtn: typeof import('./../src/components/Whitebtn/index.vue')['default']
  }
}
