// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Article: typeof import('./components/Article/index.vue')['default']
    Authorlayout: typeof import('./components/Authorlayout/index.vue')['default']
    Basicinput: typeof import('./components/Basicinput/index.vue')['default']
    Bbsarticle: typeof import('./components/Bbsarticle/index.vue')['default']
    Commentcontent: typeof import('./components/Commentcontent/index.vue')['default']
    Commentfont: typeof import('./components/Commentfont/index.vue')['default']
    Commentsmile: typeof import('./components/Commentsmile/index.vue')['default']
    Dialog: typeof import('./components/Dialog/index.vue')['default']
    Footer: typeof import('./components/Footer/index.vue')['default']
    GlobalNotice: typeof import('./components/GlobalNotice/index.vue')['default']
    Goods: typeof import('./components/Goods/index.vue')['default']
    Greenbtn: typeof import('./components/Greenbtn/index.vue')['default']
    Header: typeof import('./components/Header/index.vue')['default']
    Headerrecategory: typeof import('./components/Headerrecategory/index.vue')['default']
    Login: typeof import('./components/Login/index.vue')['default']
    Message: typeof import('./components/Message/index.vue')['default']
    Mobile: typeof import('./components/Mobile/index.vue')['default']
    Morebtn: typeof import('./components/Morebtn/index.vue')['default']
    Msgconfirm: typeof import('./components/Msgconfirm/index.vue')['default']
    NotFound: typeof import('./components/NotFound/index.vue')['default']
    Postcomment: typeof import('./components/Postcomment/index.vue')['default']
    Postdownload: typeof import('./components/Postdownload/index.vue')['default']
    Postmusic: typeof import('./components/Postmusic/index.vue')['default']
    Postvideo: typeof import('./components/Postvideo/index.vue')['default']
    Publishcategory: typeof import('./components/Publishcategory/index.vue')['default']
    Publishcomment: typeof import('./components/Publishcomment/index.vue')['default']
    Publishrecategory: typeof import('./components/Publishrecategory/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/Search/index.vue')['default']
    Searchrecategory: typeof import('./components/Searchrecategory/index.vue')['default']
    Shopconfirm: typeof import('./components/Shopconfirm/index.vue')['default']
    Slideauthor: typeof import('./components/Slideauthor/index.vue')['default']
    Slidecomment: typeof import('./components/Slidecomment/index.vue')['default']
    Slidepost: typeof import('./components/Slidepost/index.vue')['default']
    Slideuser: typeof import('./components/Slideuser/index.vue')['default']
    Spin: typeof import('./components/Spin/index.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    TextareaInput: typeof import('./components/TextareaInput/index.vue')['default']
    Tinymce: typeof import('./components/Tinymce/index.vue')['default']
    Usercenterlayout: typeof import('./components/Usercenterlayout/index.vue')['default']
    Vipconfirm: typeof import('./components/Vipconfirm/index.vue')['default']
    Wangeditor: typeof import('./components/Wangeditor/index.vue')['default']
    Whitebtn: typeof import('./components/Whitebtn/index.vue')['default']
  }
}
